### Criação de um usuário
POST http://localhost:3333/users
Content-Type: application/json

{
    "firstName": "User 01",
    "lastName": "User 01",
    "email": "user5@email.com",
    "password": "123456"
}
